"""empty message

Revision ID: 0664401cf855
Revises: cfb96943f878
Create Date: 2021-07-18 16:51:29.665839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0664401cf855'
down_revision = 'cfb96943f878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('trump_revealed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'trump_revealed')
    # ### end Alembic commands ###
