"""empty message

Revision ID: 2640e3dce331
Revises: 
Create Date: 2021-06-27 17:07:14.701932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2640e3dce331'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('red_score', sa.Integer(), nullable=True),
    sa.Column('blue_score', sa.Integer(), nullable=True),
    sa.Column('highest_bid', sa.Integer(), nullable=True),
    sa.Column('bid_winner', sa.Enum('RED', 'BLUE', name='team'), nullable=True),
    sa.Column('trump', sa.Enum('SPADE', 'HEART', 'CLUB', 'DIAMOND', name='cardsuite'), nullable=True),
    sa.Column('bid_stack', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('team', sa.Enum('RED', 'BLUE', name='team'), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=False)
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Enum('JACK', 'NINE', 'ACE', 'TEN', 'KING', 'QUEEN', 'EIGHT', 'SEVEN', name='cardnumber'), nullable=True),
    sa.Column('suite', sa.Enum('SPADE', 'HEART', 'CLUB', 'DIAMOND', name='cardsuite'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.drop_table('player')
    op.drop_table('game')
    # ### end Alembic commands ###
