"""empty message

Revision ID: 7d455938f93d
Revises: d58bcecc674b
Create Date: 2021-07-01 01:25:03.291006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d455938f93d'
down_revision = 'd58bcecc674b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('aukat_set', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'aukat_set')
    # ### end Alembic commands ###
