"""empty message

Revision ID: 9bc25a7447c8
Revises: 11eb36d4c534
Create Date: 2021-06-05 18:01:58.394390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc25a7447c8'
down_revision = '11eb36d4c534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'order')
    # ### end Alembic commands ###
