"""empty message

Revision ID: cfb96943f878
Revises: 7d455938f93d
Create Date: 2021-07-03 11:53:31.696150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb96943f878'
down_revision = '7d455938f93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('red_points', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('blue_points', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('round', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'round')
    op.drop_column('game', 'blue_points')
    op.drop_column('game', 'red_points')
    # ### end Alembic commands ###
