"""empty message

Revision ID: d58bcecc674b
Revises: 2640e3dce331
Create Date: 2021-06-27 22:48:36.554696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58bcecc674b'
down_revision = '2640e3dce331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('trump_order', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('double', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('double_counter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'double_counter')
    op.drop_column('game', 'double')
    op.drop_column('game', 'trump_order')
    # ### end Alembic commands ###
